# Generated by Django 3.0 on 2022-09-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=9)),
                ('country', models.CharField(max_length=2)),
                ('purchase', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('net', models.FloatField()),
                ('Vat', models.FloatField()),
            ],
        ),
    ]
